### ISSUE TITLE
Where is the model file?

### ISSUE THREAD

**Issue by jsdd25** [oravus/SeqMatchNet#5]
Hello! Thanks for your great work.
Could you please provide the download link of the trained model file? Thank you very much!

**Comment by oravus** [comment]
Hi @jsdd25, the Oxford trained model [download link](https://cloudstor.aarnet.edu.au/plus/s/y27PHvmZ2xpmcId) is now in the Readme. You can test it as follows:
`python main.py --mode test --seqL 5 --pooling -dataset oxford-v1.0 --split test --resume Dec28_20-40-39_l5_ox10_MoP_negMoP/
`
